export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_USER_DATA = 'SET_USER_DATA';
export const REMOVE_USER_DATA = 'REMOVE_USER_DATA';
export const SET_PROFILE_PAGE_DATA = 'SET_PROFILE_PAGE_DATA';
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_SINGLE_PROJECT = 'SET_SINGLE_PROJECT';
export const SET_PROJECT_PARTICIPANT = 'SET_PROJECT_PARTICIPANT';
export const SET_PROJECT_COMMENTS = 'SET_PROJECT_COMMENTS';